#!/bin/sh

cd $HOME
git init
git remote add -t master -f origin https://github.com/icgw/dotfiles.git

curl -sL install-node.now.sh/lts | bash
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
